[build]
  command = "npm install && npm run build"
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@neondatabase/serverless"]

[[redirects]]
  from = "/partners"
  to = "/?partner=1"
  status = 302

[[redirects]]
  from = "https://jrcpartner.hlsr.app/*"
  to = "https://jrc.hlsr.app/?partner=1"
  status = 302
  force = true

[build.processing]
  skip_processing = false

[secrets_scanning]
  omit_paths = ["node_modules"]
  omit_keys = ["BOARD_ACCESS_CODE"]
